<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.cache.jcache.interceptor.JCacheErrorHandlerTests" tests="6" skipped="0" failures="0" errors="0" timestamp="2023-03-06T07:56:08" hostname="DESKTOP-VGJP1PJ" time="0.342">
  <properties/>
  <testcase name="clearFail()" classname="org.springframework.cache.jcache.interceptor.JCacheErrorHandlerTests" time="0.149"/>
  <testcase name="getFailPutExceptionFail()" classname="org.springframework.cache.jcache.interceptor.JCacheErrorHandlerTests" time="0.037"/>
  <testcase name="evictFail()" classname="org.springframework.cache.jcache.interceptor.JCacheErrorHandlerTests" time="0.063"/>
  <testcase name="putFail()" classname="org.springframework.cache.jcache.interceptor.JCacheErrorHandlerTests" time="0.029"/>
  <testcase name="getFail()" classname="org.springframework.cache.jcache.interceptor.JCacheErrorHandlerTests" time="0.03"/>
  <testcase name="getPutNewElementFail()" classname="org.springframework.cache.jcache.interceptor.JCacheErrorHandlerTests" time="0.03"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
